### ISSUE TITLE
Error in compiling

### ISSUE THREAD

**Issue by marcoc610** [cblomart/vsphere-graphite#59]
Trying to compile with the steps in "Execute vsphere-graphite in shell"

` go get github.com/cblomart/vsphere-graphite`

I get these errors

```
# github.com/cblomart/vsphere-graphite
golang/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:269:50: undefined: gitTag
golang/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:269:58: undefined: gitShortCommit
golang/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:269:74: undefined: gitStatus
```

If I comment-out the line
```
log.Printf("Version information: %s - %s (%s)", gitTag, gitShortCommit, gitStatus)
```
the compilation succeeds.

Am I misssing some steps?

**Comment by cblomart** [comment]
You need to generate the necessary files:

(in the vsphere-graphite folder)

```bash
# go generate ./... 
```

**Comment by cblomart** [comment]
You also will need to have different tools installed:

```bash
# go get github.com/cblomart/git-version
# go get github.com/pquerna/ffjson
```

**Comment by marcoc610** [comment]
I am not a developer and I am quite sure that this approach is ugly and maybe wrong, but it works.

```
$ go get github.com/cblomart/vsphere-graphite
# github.com/cblomart/vsphere-graphite
golang/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:269:50: undefined: gitTag
golang/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:269:58: undefined: gitShortCommit
golang/src/github.com/cblomart/vsphere-graphite/vsphere-graphite.go:269:74: undefined: gitStatus
```
Then I added what suggested...
```
$ go get github.com/cblomart/git-version
$ go get github.com/pquerna/ffjson
```
... I `generate`d ...
```
$ cd $GOPATH/src/github.com/cblomart/vsphere-graphite
$ PATH=$PATH:$GOPATH/bin go generate
2018/08/08 14:33:52 Commit: b926f356d1ac810969466ec11a4290d9a4e7c8df
2018/08/08 14:33:52 Short Commit: b926f35
2018/08/08 14:33:52 Tag:
2018/08/08 14:33:52 Status: clean
```
... and at this point the compilation works
```
$ go get github.com/cblomart/vsphere-graphite
```

Using the new executable, the log shows some version information
```
Aug 08 14:46:58 xxlnxsrv05 systemd[1]: Started VSphere2Graphite.
Aug 08 14:46:58 xxlnxsrv05 vsphere-graphite[19237]: 2018/08/08 14:46:58 Version information: - - b926f35 (clean)
Aug 08 14:46:58 xxlnxsrv05 vsphere-graphite[19237]: 2018/08/08 14:46:58 Starting daemon: vsphere-graphite
Aug 08 14:46:59 xxlnxsrv05 vsphere-graphite[19237]: 2018/08/08 14:46:59 Initializing vCenter XXXXX
...
```

**Comment by cblomart** [comment]
Go generate is a generic golang feature.
Admittedly it isn’t done « go get ».

There are two goals in here:
1/ffjson
the first versions didn’t work without go generate. Now if go generate wasn’t done it will fallback to standard Json encoder.

2/Version info
with the latest bug I wanted to have a better view on version used and be able to check it in the logs.
There is no good solution there.
Either provide compile time variable or define a file with the necessary informations in variables.
« git-version » does the latter. Once again these informations are not present if one simply does go get.
Golang wouldn’t standardise on git information (tag/commit) because it supports different versioning systems.
Here the fact that one cannot compile simply with « go get » obliges everyone to use go generate.

If anyone has a solution to control version information in golang that works natively with « go get »: I am all ears!
In the meantime and if it is too annoying i can include a default file with bogus version information.

**Comment by marcoc610** [comment]
> In the meantime and if it is too annoying i can include a default file with bogus version information.

No, it is not _too_ annoying, but in my opinion it would be nice to have that bogus version information.

**Comment by cblomart** [comment]
I added a dummy ```version.go``` file.
