### ISSUE TITLE
Memleak?

### ISSUE THREAD

**Issue by dupondje** [cblomart/vsphere-graphite#93]
Hi,

I upgraded to the most recent version, but I notice that vsphere-graphite starts using alot of memory.
I'm using the Prometheus option.

Attached the pprof
![pprof001](https://user-images.githubusercontent.com/723195/57922509-4046e800-78a0-11e9-8062-1c748729821f.png)

I tried to find out the cause, but didn't find it directly.

Any idea's ? :)

**Comment by cblomart** [comment]
On the changes on last releases...

There was a bug with Prometheus style backends. Meaning backends that pull data.
The consequences of this bug is that all metrics where not always sent.

The principle of pull backends is as following:

A channel waits for requests.
When a request is made, it will start the collection process.
This process will send metrics on one channel and a signal on another channel to notify that it has finished.
When the collection process is finished the points are formatted in the desired format and sent to the backend.

I first implemented this considering that when the finish signal is sent, all points would be in the channel.

Naturally they are not. So I added a timer to consider that collection is finished only when points are not received for a certain amount of time (I.e 100ms).

So now vsphere-graphite really caches all points before sending them.
This is, i think, a sensible explanation of increased memory usage.

To get back on the principle, pull backend (Prometheus) needs to cache all metrics which required memory 😐

I looked up if I could stream the points to the backend (chunked encoding) but Prometheus needs all metrics with the same name in a succession so ordering the whole thing is required (bummer).

If you want to check further you may want to limit the amount of managed objects seen by vsphere-graphite and increase them incrementally. Memory should grow accordingly.
Comparison with a push backend may be useful as memory shouldn’t grow as much.

**Comment by dupondje** [comment]
Well I think the issue is non-related to this. Cause initially the memory usage is quite ok, and it runs fine for hours. But at some moment memory starts increasing, until the process gets killed by the OOM killer.

For example
May 22 06:30:35 xxxx vsphere-graphite[26508]: 2019/05/22 06:30:35 Memory usage : sys=5.3G alloc=1.7G
May 22 06:31:10 xxxx vsphere-graphite[26508]: 2019/05/22 06:31:10 Memory usage : sys=5.4G alloc=1.6G
May 22 06:32:34 xxxx vsphere-graphite[26508]: 2019/05/22 06:32:34 Memory usage : sys=5.4G alloc=1.6G
May 22 06:33:26 xxxx vsphere-graphite[26508]: 2019/05/22 06:33:26 Memory usage : sys=5.4G alloc=1.7G

After a restart of the process, and some minutes of running (so surely already collected all the metrics):
May 22 08:06:21 xxxx vsphere-graphite[454]: 2019/05/22 08:06:21 Memory usage : sys=410M alloc=60.6M
May 22 08:08:15 xxxx vsphere-graphite[454]: 2019/05/22 08:08:15 Memory usage : sys=418.9M alloc=51.9M
May 22 08:08:54 xxxx vsphere-graphite[454]: 2019/05/22 08:08:54 Memory usage : sys=418.9M alloc=58M
May 22 08:10:03 xxxx vsphere-graphite[454]: 2019/05/22 08:10:03 Memory usage : sys=418.9M alloc=61.5M

This amount of memory seems normal. But more seems to leak somewhere.

Also there might be another way to implement the collection for Prometheus.
The collection of metrics could happen like every 'collect_interval' time (take every minute for example), and then when a request arrives on the /metrics, it should just report the already collected and in-memory metrics.
This would also cause less overhead when multiple Prometheus instances (for HA for example), collects the same metrics. Now this causes 2 calls to the vcenter, and might be reduced to 1 via this method.
But thats another discussion :)

**Comment by dupondje** [comment]
Seems we are leaking goroutines:
goroutine 201290 [chan send, 252 minutes]:
github.com/cblomart/vsphere-graphite/vsphere.ProcessMetric(0x19b9790, 0xc432f55c20, 0x5ce76ed2, 0xc432b1e500, 0xc42003a220, 0x14, 0xc429f848a0, 0xe, 0xc4200ba028, 0xc430d8ac70)
	/home/jean-louis/go/src/github.com/cblomart/vsphere-graphite/vsphere/vsphere.go:765 +0xb4f
created by github.com/cblomart/vsphere-graphite/vsphere.ExecuteQueries
	/home/jean-louis/go/src/github.com/cblomart/vsphere-graphite/vsphere/vsphere.go:573 +0x485

Might be caused by concurrent calls to the /metrics page? Think it should be synced somewhere.

**Comment by cblomart** [comment]
I look at adding runtime.numgoroutines when showing memory statistics.
I think that would be a first step into looking into goroutines leak...

**Comment by cblomart** [comment]
I added some reporting on goroutines on the branch goroutines 3e9b06c 
Can you check the result? (see if it effectevely leaks goroutines)

**Comment by dupondje** [comment]
First Run:
2019/05/27 09:43:23 Memory usage : sys=478.2M alloc=157.5M
2019/05/27 09:43:23 GoRoutines : 11223

After some concurrent runs:
2019/05/27 09:46:21 Memory usage : sys=954.5M alloc=267.5M
2019/05/27 09:46:21 GoRoutines : 22744

You can very easily simulate the issue by just calling the /metrics page concurrently, then you'll have leaks.

**Comment by cblomart** [comment]
I added a syncgroup to process metrics... there should be less leaked goroutines 7eb3651

**Comment by dupondje** [comment]
Seems to have stable GoRoutines count now :)
Worked fine for hours, but suddenly it stopped reporting GoRoutines and Memory usage info, and no data returned (but the queries were running).

Added some debug now, and restarted. Lets see if it happens again.

**Comment by dupondje** [comment]
Happend again.
In attachment the running GoRoutines at this moment.

It still runs queries, but they are not processed/returned.
[goroutines.txt](https://github.com/cblomart/vsphere-graphite/files/3227325/goroutines.txt)

**Comment by dupondje** [comment]
https://github.com/cblomart/vsphere-graphite/blob/7eb36510849ef95d39d71b5ab077ecf40a5d1624/vsphere/vsphere.go#L546

This should also wg.Done()?

**Comment by cblomart** [comment]
It should... 
i'll add a defer as in 
https://github.com/cblomart/vsphere-graphite/blob/7eb36510849ef95d39d71b5ab077ecf40a5d1624/vsphere/vsphere.go#L169

**Comment by cblomart** [comment]
updated in  a3f10fa

**Comment by dupondje** [comment]
Not a single goroutine leak anymore (and no memory leak) since the last commit :)
Seems like this is fixed!

**Comment by cblomart** [comment]
merged changes to master.
